services:
  be1:
    build:
      context: ./admincmsmartschoolbackend
    env_file:
      - ./admincmsmartschoolbackend/.env
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@newluminoed-db-1:5432/${DB_NAME}?sslmode=disable
      - PORT=8080
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - webnet
      - newluminoed_app-network

networks:
  webnet:
    driver: bridge
  newluminoed_app-network:
    external: true
